config/routes.rb
Rails.application.routes.draw do

  	devise_for :users

  	resources :users, only: [:index, :show, :edit, :update]

	#notes関連のルーティン
	resources :notes

	root 'home#top'
	get '/about' => 'home#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord

  belongs_to :user

  # 値があるかどうか
  validates :title,  presence: true
  
  # 値があるかどうか、140文字以下か
  validates :content, presence: true, length: {maximum: 140}

  # user_idがあるかどうか
  validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable, :validatable
	
	has_many :notes

	validates :name, presence: true
	validates :email, presence: true, uniqueness: true

	  # 以下にset_imageメソッドを定義してください
	  def set_image(file)
	  	#fileが空でなかったら
	    if !file.nil?
	      #URLを取得
	      file_name = file.original_filename
	      # public/user_imageにurlを保存
	      File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
	      # @userのimageセッターを使って、file_nameをセット
	      self.image = file_name
	    end
	  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  include ApplicationHelper

  # privateメソッドを定義し、deviseの新規登録フォームでnameを受け取れるように
  private
  
  #rails 5.0.0以降はforメソッドが使えないらしいからpermitメソッドに変更
  #参考サイト　http://qiita.com/karunru/items/2d8e11556213d536f7df

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  

  def default_url_options() {privateIp: '172.17.0.3', containerPort: '3000', languageName: 'rails'}.merge(super) end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
    if user_signed_in?
      # 変数@noteにNoteクラスのインスタンスを代入
      @note = Note.new
      # 変数@notesにNoteクラスのインスタンスの配列を降順で代入してください
      @notes = Note.all.order(created_at: :desc)
    else
      @message = "ようこそmyappへ！"
    end
    
  end

  def about
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  #ユーザがログインしているかどうか
  before_action :authenticate_user!

  before_action :correct_user, only: [:edit, :update]

  before_action :set_note, only:[:show, :edit, :update, :destroy]

  # def new
  # 	#newでインスタンスを作っておくことで投稿に失敗した時の初期値をフォームに表示させることができる
  # 	@note = Note.new
  # end

  def create
    @note = current_user.notes.build(note_params)

    if @note.save
      redirect_to @note, notice: "投稿が保存されました"
    else
 
    @notes =Note.all.order(created_at: :desc)
      
    # renderメソッドで表示するビューが、トップページに
    render 'home/top'
      
    end
  end

  def index
    @notes = Note.all.order(created_at: :desc)
  end

  def show
  end

  def edit
  end

  def update
    # @note = Note.new(note_params)
    # @note.title = params[:note][:title]
    # @note.content = params[:note][:content]
    # @note.save

    # showアクションにリダイレクト
    # redirect_to note_path(@note.id)

    # updateメソッドを使うことでセッターに値を入れてsaveしてーを簡単にできる
    if @note.update(note_params)
      redirect_to @note, notice: '投稿が更新されました'
    else
      render :edit
    end
  end

  def destroy
    @note.destroy

    #indexアクションにリダイレクト
    redirect_to notes_path, notice: '投稿が削除されました'
  end

  private

  def set_note
  	@note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :content)
  end

  def correct_user
    note = Note.find(params[:id])
    # noteを投稿したユーザーを取得し、current_user?メソッドの引数に渡してください
      if !current_user?(note.user)
        redirect_to root_path, alert: '許可されていないページです'
      end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #ユーザがログインしているかどうか
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]



  def index
    @users = User.all
  end

  def show
    # @userのidをuser_idとしてもつnoteを@notesに代入
    # @userはbefore_actionで定義済み

    # @notes = Note.where(user_id: @user.id)
    #has_manyで定義したから使える

    @notes = @user.notes

  end

  #deviseのフォームがあるためいらない
  # def new
  #   @user = User.new
  # end

  def edit
  end

  #deviseのフォームがあるためいらない
  # def create
  #   @user = User.new(user_params)
  #   # アップロードされる画像をparams[:user][:image]で受け取る
  #   file = params[:user][:image]

  #   @user.set_image(file)

  #   if @user.save
  #     redirect_to @user, notice: 'ユーザーが保存されました'
  #   else
  #     render :new
  #   end
  # end

  def update
    file = params[:user][:image]
    @user.set_image(file)

    if @user.update(user_params)
      redirect_to @user, notice: 'ユーザー情報が更新されました'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'ユーザーが削除されました'
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email)
    end

    def correct_user
      user = User.find(params[:id])
      # if文をcurrent_user?ヘルパーを用いて書き換えてください
      if !current_user?(user)
        redirect_to root_path, alert: '許可されていないページです'
      end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user?(user)
    current_user.id == user.id
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def image_for(user)
    	if user.image
      		image_tag "/user_images/#{user.image}", class: "profile_img"
    	else
      		image_tag "sample.jpg", class: "profile_img" 
    	end
  	end

end

app/views/home/about.html.erb
  <h1>Gatebookとは？</h1>
  <p>GatebookとはRuby on Railsというフレームワークを駆使した、<br>記事投稿SNSサービスです。<br>近況やつぶやきを投稿し、サービス上の友達と楽しくコミュニケーションできます。</p>

app/views/home/top.html.erb
<% if user_signed_in? %>
  <aside class="sidebar">
    <%= render 'notes/form' %>
  </aside>
  <ul class="notes">
    <h2>投稿の一覧</h2>
    <%= render @notes %> 
  </ul>
<% else %>
  <div class="top-wrapper">
    <div class="register-wrapper">
      <h1><%= @message %></h1>
      <%= link_to "新規登録", new_user_registration_path, class: "btn btn-large register-btn" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="navbar">
    <div class="container">
      <div id="logo"><%= link_to "myapp", root_path %></div>
      <% if user_signed_in? %>
        <ul class="header-right">

          <li><%= link_to "投稿一覧", notes_path %></li>
          <li><%= link_to "ユーザ一覧", users_path %></li>
          <li><%= link_to current_user.name + "さん", current_user %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul class="header-right">
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        </ul>
      <% end %>
    </div>
  </header>

  <div class="container">
    <p class="alert alert-success"><%= notice %></p>
    <p class="alert alert-danger"><%= alert %></p>

    <%= yield %>

  </div>

  <div class="container">

    <footer class="footer">
      <div class="small">
        &copy; 2017 Yuta Mizogami
      </div>
    </footer>
  </div>
</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @note.errors.count %>件のエラーがあります。</h2>

      <ul>
        <% @note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  タイトル
  <%= f.text_field :title, { class: "form-control title-field" } %>
  内容
  <%= f.text_area :content, { class: "form-control content-field" } %>
  <%= f.submit "保存", { class: "btn primary-btn" } %>
  
<% end %>

app/views/notes/_note.html.erb
<li>
  <!-- ユーザの画像 -->
  <%= image_for(note.user) %>
  <!-- ユーザの名前 -->
  <span class="user-name">
    <%= note.user.name %>
  </span>
  <!-- ユーザの投稿内容 -->
  <span class="content">
    <%= link_to note.title, note_path(note.id) %>
  </span>
</li>

app/views/notes/edit.html.erb
<h1>投稿を編集する</h1>
<%= render 'form' %>

app/views/notes/index.html.erb
<!-- サクセスメッセージの表示 -->
<!-- <p id="notice" class="alert alert-success">
  <%= notice %>
</p> -->

<h1>投稿の一覧</h1>
<ul class="notes">
  <%= render @notes %>
</ul>

app/views/notes/new.html.erb
<h1>新規投稿する</h1>
<%= render 'form' %>

app/views/notes/show.html.erb
<!-- サクセスメッセージの表示 -->
<!-- <p id="notice" class="alert alert-success">
  <%= notice %>
</p> -->


<h2>タイトル</h2>
<p><%= @note.title %></p>
<h2>内容</h2>
<p><%= @note.content %></p>

<% if current_user?(@note.user) %> 
  <%= link_to "編集", edit_note_path(@note.id), class: "btn edit-btn" %>
  <%= link_to "削除", note_path(@note.id), method: "delete", class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
       <p><%= @user.errors.count %>件のエラーがあります。</p>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  名前
  <%= f.text_field :name, class: "form-control name-field" %>

  メールアドレス
  <%= f.text_field :email, class: "form-control email-field" %>

  プロフィール画像
  <%= f.file_field :image, class: "form-control image-field" %>

  <%= f.submit '保存', class: "btn primary-btn" %>

<% end %>

app/views/users/edit.html.erb
<h1>ユーザの編集</h1>

<%= render 'form' %>

<%= link_to 'ユーザー一覧へ', users_path %>

app/views/users/index.html.erb
<h1 class="heading">ユーザ一覧</h1>


<ul class="user-list">
  <% @users.each do |user| %>
    <li>
      <!-- imageがあればそれを、なければデフォルトを表示させるメソッドの呼び出し -->
      <%= image_for(user) %>
      <%= link_to user.name, user %> |
      <%= user.email %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>新規ユーザ作成</h1>

<%= render 'form' %>

<%= link_to '戻る', users_path %>

app/views/users/show.html.erb
<aside class="sidebar">  
  <section>
    <span class="label">プロフィール画像</span>
    <h3 class="user-info">
      <%= image_for(@user) %>
    </h3>
  </section>
  
  <section>
    <span class="label">ユーザー</span>
    <h3 class="user-info"><%= @user.name %></h3>
  </section>
  
  <section>
    <span class="label">メールアドレス</span>
    <h3 class="user-info"><%= @user.email %></h3>
  </section>
  
  <!-- 以下をif文で囲み、ログイン中のユーザーと@userが同じ場合のみ表示してください -->
  <% if current_user.id == @user.id %>
    <section>
      <small><%= link_to 'プロフィールを編集', edit_user_path(@user) %></small>
    </section>
  <% end %>

  <br>
</aside>

<ul class="notes">
  <%= render @notes %>
</ul>